spring.jpa.hibernate.ddl-auto: none

spring.datasource.url: jdbc:mysql://localhost:3306/diplom
spring.datasource.username: root
spring.datasource.password: testskill

flyway.url: jdbc:mysql://localhost:3306
flyway.schemas: diplom
flyway.user: root
flyway.password: testskill
flyway.locations: filesystem:db/migration

config:
  captcha:
    timeout: 10
    image:
      width: 110
      height: 35
  post:
    minlength:
      title: 3
      text: 50
  comment:
    minlength:
      text: 10

upload:
  path: \s:\Education\SKILLBOX\JAVA\Diplom\uploads_image
  maxSize: 1048576
  expansion: jpg, png
  randomPart:
    value: 3
    length: 2

avatar:
  path: \s:\Education\SKILLBOX\JAVA\Diplom\uploads_avatar