spring.jpa.hibernate.ddl-auto: none
spring.datasource.url: jdbc:mysql://localhost:3306/diplom
spring.datasource.username: root
spring.datasource.password: testskill

flyway.user: root
flyway.password: testskill
flyway.schemas: diplom
flyway.url: jdbc:mysql://localhost:3306
flyway.locations: filesystem:db/migration
