spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url:
    username:
    password:

config:
  password:
    minlength: 6
  captcha:
    timeout: 10
    image:
      width: 110
      height: 35
  post:
    minlength:
      title: 3
      text: 50
  comment:
    minlength:
      text: 10
  restore:
    timeout: 10

upload:
  path: /project/diplom/uploads
  maxSize: 1048576
  expansion: jpg, png
  randomPart:
    value: 3
    length: 2

avatar:
  width: 90
  height: 90
  default: /default-1.png

email:
  host:
  port:
  username:
  password: